batch_size = 1
seq_length = 8192
num_layers = 62
hidden_size = 3072
ffn_hidden_size = 0
moe_ffn_hidden_size = 1536
num_experts_routed_to = 8
num_moe_layers = 62
num_dense_layers = 0
mtp_num_layers = 0
padded_vocab_size = 200064
shared_expert_ffn_hidden_size = 0
num_query_groups = 8
num_attention_heads = 48
kv_channels = 128
attention_output_gate = False
query_projection_size = kv_channels * num_attention_heads
query_projection_to_hidden_size_ratio = query_projection_size / hidden_size
swiglu = True
